# Generated by Django 4.1.7 on 2023-05-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicbeats", "0007_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="movie",
        ),
    ]
