# Generated by Django 4.1.7 on 2023-05-14 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musicbeats", "0008_remove_song_movie"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watchlater",
            new_name="Playlist",
        ),
    ]
